### ISSUE TITLE
Do we want to merge this into infrastructure?

### ISSUE THREAD

**Issue by michielbdejong** [pierreozoux/static-website-implementation#1]
Right now https://github.com/indiehosters/infrastructure uses per-user WordPress/Nginx instances, with one server-wide haproxy instance in front. I can imagine pooling all the Nginx users into one Nginx container is more efficient, and same for WordPress. What do we want to do with this? Pool just the Nginx users together and leave the WordPress ones as per-user? Maybe at least we should move the content of this repo into a PR on the infrastructure repo, to make it clearer whether or not we want to merge this?

**Comment by pierreozoux** [comment]
Yes, we need to merge this. I like the idea of one nginx for all static content, because there is no security issue. For wordpress, as there is php, I would prefer one container per wordpress.

**Comment by pierreozoux** [comment]
I'll take care of that.

**Comment by michielbdejong** [comment]
@pierreozoux ping

**Comment by michielbdejong** [comment]
btw I moved https://github.com/indiehosters/indiehosters-docker-bash out of https://github.com/indiehosters/indiehosters - we might want to rename https://github.com/indiehosters/indiehosters to https://github.com/indiehosters/indiehosters-coreos?

**Comment by pierreozoux** [comment]
Yep, this is moved now.
Btw, I thought it would be better if you move your implementation under your name. I did it with IndieHosters, now it is IndiePaaS under my name, then we'll have to change this repo to point it to our 2 repos. What do you think?

**Comment by michielbdejong** [comment]
OK, done!
